---
- name: Install Selected APT Packages
  apt: name={{ item }} state=latest
  with_items: apt_packages
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Selected YUM Packages
  yum: name={{ item }} state=latest
  with_items: yum_packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
