---
- name: Try If Developer Group Exists
  group: name=studev
         state=present

- name: Try If SUDO (wheel) Group Exists
  group: name=wheel
         state=present

- name: Add Sudo User
  user: name={{ item }} 
        comment="User" 
        shell=/bin/bash 
        groups=studev,wheel
        append=yes
  with_items: users

- name: Set SSH Authorized Key
  authorized_key: user={{ item }}
                  key="{{ lookup('file', 'keys/id_rsa-{{ item }}.pub') }}"
  with_items: users